version: 2

before:
  hooks:
    - sh -c 'VERSION=${GORELEASER_CURRENT_TAG:-dev}; sed -i "s/var Version = \".*\"/var Version = \"${VERSION}\"/" version/version.go'

changelog:
  use: github
  groups:
    - title: ✨Features
      regexp: "^feat(\\(.+\\))?!?:\\s.*$"
      order: 0
    - title: 🐞Bug Fixes
      regexp: "^fix(\\(.+\\))?!?:\\s.*$"
      order: 1
    - title: ⚙️Code Refactoring
      regexp: "^refactor(\\(.+\\))?!?:\\s.*$"
      order: 2
    - title: 🕜Performance Improvements
      regexp: "^perf(\\(.+\\))?!?:\\s.*$"
      order: 3
    - title: 🚀Chores
      regexp: "^chore(\\(.+\\))?!?:\\s.*$"
      order: 4
    - title: 🌈Style Improvements
      regexp: "^style(\\(.+\\))?!?:\\s.*$"
      order: 5
    - title: ✅Tests
      regexp: "^test(\\(.+\\))?!?:\\s.*$"
      order: 6
    - title: 📄Documentations
      regexp: "^docs(\\(.+\\))?!?:\\s.*$"
      order: 7
    - title: ⏪Reverts
      regexp: "^revert(\\(.+\\))?!?:\\s.*$"
      order: 8
    - title: Others
      order: 999
