blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/opensraph/template.go/blob/main/README.md
    about: Check the documentation for common questions and usage examples
  - name: Discussions
    url: https://github.com/opensraph/template.go/discussions
    about: Ask questions and discuss ideas with the community
