# Configuration for no-response - https://github.com/lee-dohm/no-response

name: no-response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00 UTC

jobs:
  no-response:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Number of days of inactivity before an Issue is closed for lack of response
          daysUntilClose: 14
          # Label indicating that a response from the original author is required
          responseRequiredLabel: more-information-needed
          # Comment to post when closing an Issue for lack of response. Set to `false` to disable.
          closeComment: >
            Without additional information, we are unfortunately not sure how to
            resolve this issue. We are therefore reluctantly going to close this
            bug for now. Please don't hesitate to comment on the bug if you have
            any more information for us; we will reopen it right away!
            Thanks for your contribution.
